version: "3"

services:
  api:
    hostname: api
    image: failed-banks:latest
    ports:
      - 9000:7000
    environment:
      - DB_USERNAME=XXX
      - DB_PASS=XXX
      - DB_HOST=fdic_db
    networks:
      fdic_fdic_db_network:


networks:
  fdic_fdic_db_network:
    external: true
