version: "3"

services:
  frontend:
    hostname: frontend
    image: fdic-ui:latest
    ports:
      - "8180:80"
    networks:
      - default
  api:
    hostname: api
    image: failed-banks:latest
    ports:
      - 9000:7000
    environment:
      - DB_USERNAME=XXX
      - DB_PASS=XXX
      - DB_HOST=fdic_db
    networks:
      - fdic_fdic_db_network
      - default


networks:
  fdic_fdic_db_network:
    external: true
